language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g grunt-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - grunt start > /dev/null &
  - grunt update-webdriver
  - sleep 1 # give server time to start
script:
  - grunt eslint
  - grunt karma:travis
  - grunt protractor
after_script:
  - grunt coveralls
